-- FOREIGN KEYs de PC_PRECIO_HISTORIAL (Etapa C) — idempotente; lo ejecuta DbBootstrap DESPUÉS de crear todas las tablas.
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_PRECIO_HISTORIAL_VarianteId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_PRECIO_HISTORIAL')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_VARIANTES')
    ALTER TABLE [PC_PRECIO_HISTORIAL] ADD CONSTRAINT [FK_PC_PRECIO_HISTORIAL_VarianteId]
        FOREIGN KEY ([VarianteId]) REFERENCES [PC_VARIANTES]([Id]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PC_PRECIO_HISTORIAL_VarianteId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_PRECIO_HISTORIAL')
    CREATE INDEX [IX_PC_PRECIO_HISTORIAL_VarianteId] ON [PC_PRECIO_HISTORIAL]([VarianteId]);
GO
