-- FOREIGN KEYs de PC_VARIANTES — idempotente; lo ejecuta DbBootstrap DESPUÉS de crear todas las tablas.
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_VARIANTES_ProductoId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_VARIANTES')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_PRODUCTOS')
    ALTER TABLE [PC_VARIANTES] ADD CONSTRAINT [FK_PC_VARIANTES_ProductoId]
        FOREIGN KEY ([ProductoId]) REFERENCES [PC_PRODUCTOS]([Id]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_VARIANTES_TallaId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_VARIANTES')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_TALLAS')
    ALTER TABLE [PC_VARIANTES] ADD CONSTRAINT [FK_PC_VARIANTES_TallaId]
        FOREIGN KEY ([TallaId]) REFERENCES [PC_TALLAS]([Id]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_VARIANTES_ColorId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_VARIANTES')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_COLORES')
    ALTER TABLE [PC_VARIANTES] ADD CONSTRAINT [FK_PC_VARIANTES_ColorId]
        FOREIGN KEY ([ColorId]) REFERENCES [PC_COLORES]([Id]);
GO
