-- FOREIGN KEYs de PC_MOVIMIENTOS_STOCK — idempotente; lo ejecuta DbBootstrap DESPUÉS de crear todas las tablas.
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_MOVIMIENTOS_STOCK_VarianteId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_MOVIMIENTOS_STOCK')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_VARIANTES')
    ALTER TABLE [PC_MOVIMIENTOS_STOCK] ADD CONSTRAINT [FK_PC_MOVIMIENTOS_STOCK_VarianteId]
        FOREIGN KEY ([VarianteId]) REFERENCES [PC_VARIANTES]([Id]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_MOVIMIENTOS_STOCK_DepositoId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_MOVIMIENTOS_STOCK')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_DEPOSITOS')
    ALTER TABLE [PC_MOVIMIENTOS_STOCK] ADD CONSTRAINT [FK_PC_MOVIMIENTOS_STOCK_DepositoId]
        FOREIGN KEY ([DepositoId]) REFERENCES [PC_DEPOSITOS]([Id]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PC_MOVIMIENTOS_STOCK_DepositoDestinoId')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_MOVIMIENTOS_STOCK')
    AND EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PC_DEPOSITOS')
    ALTER TABLE [PC_MOVIMIENTOS_STOCK] ADD CONSTRAINT [FK_PC_MOVIMIENTOS_STOCK_DepositoDestinoId]
        FOREIGN KEY ([DepositoDestinoId]) REFERENCES [PC_DEPOSITOS]([Id]);
GO
